"""empty message

Revision ID: db6976d6428e
Revises: 757a94dd704d
Create Date: 2019-11-28 19:18:09.809835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db6976d6428e'
down_revision = '757a94dd704d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('broker', sa.String(), nullable=True))
    op.add_column('stock', sa.Column('date', sa.Date(), nullable=True))
    op.add_column('stock', sa.Column('price', sa.Float(), nullable=True))
    op.add_column('stock', sa.Column('tax', sa.Float(), nullable=True))
    op.add_column('stock', sa.Column('ticker', sa.String(), nullable=False))
    op.drop_column('stock', 'id')
    op.drop_column('stock', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stock', sa.Column('name', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    op.add_column('stock', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('stock', 'ticker')
    op.drop_column('stock', 'tax')
    op.drop_column('stock', 'price')
    op.drop_column('stock', 'date')
    op.drop_column('stock', 'broker')
    # ### end Alembic commands ###
